[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py311', 'py312', 'py313']
include = '\.pyi?$'
extend-exclude = '''
/(
  # Defer to paths you want to exclude
  |\.git
  |\.hg
  |\.mypy_cache
  |\.tox
  |\.venv
  |_build
  |buck-out
  |build
  |dist
)/
'''